### ISSUE TITLE
running SH2 on Hortonworks

### ISSUE THREAD

**Issue by stev-0** [aseldawy/spatialhadoop2#15]
I am trying to install and run SpatialHadoop2 on an existing Hortonworks (HDP) platfom 2.2.6. I have followed the tips in #9 and manually installed files from SpatialHadoop 2.3.2 into various locations and restarted the cluster.

I have tried so far:

bin/* files in /usr/bin
bin/* files in /usr/hdp/2.2.6.0-2800/hadoop

etc/hadoop/conf/* in /etc/hadoop/conf
etc/hadoop/conf/* in /usr/hdp/2.2.6.0-2800/hadoop/conf

share/hadoop/common/lib/* in /usr/lib/hadoop/lib
share/hadoop/common/lib/* in /usr/hdp/current/hadoop-mapreduce-client
share/hadoop/common/lib/* in /usr/hdp/current/hadoop-mapreduce-client/lib
share/hadoop/common/lib/* in /usr/hdp/2.2.6.0-2800/hadoop

I can get the shadoop script to run, however when running the command `shadoop index /mydata /mydata_idx shape:edu.umn.cs.spatialHadoop.osm.OSMPolygon sindex:grid` 

I still get the error `java.lang.ClassNotFoundException: com.vividsolutions.jts.io.ParseException` despite the jts-1.8 jar being in the 4 lib locations above. Does anyone have any other tips to get this to work on HDP?

**Comment by aseldawy** [comment]
It seems from the error message that JTS library is not loaded. Please double check the following.
1. Make sure the JTS library is on EVERY node in your cluster, not just the master node.
2. You need to restart the cluster after placing the JTS library to make sure that each machine loads it.
Please let me know if this solves your problem.

**Comment by stev-0** [comment]
The classpath on HDP is funny so that was what was causing it. I will submit a pull request for the script that worked for me in the end,
